### ISSUE TITLE
Error: Cannot find module './lib/iframe-stream.js'

### ISSUE THREAD

**Issue by dharmik-dalwadi-seaflux** [alezanai/kvs-parser#23]
Getting this error while using the FrameStream class.

## Error

```js
Error: Cannot find module './lib/iframe-stream.js'
Require stack:
- /home/dharmik/Documents/Projects/klap/sls-node-rush-salad-analysis/node_modules/kvs-parser/index.js
- /home/dharmik/Documents/Projects/klap/sls-node-rush-salad-analysis/test/issues/issue-384.js
- /home/dharmik/Documents/Projects/klap/sls-node-rush-salad-analysis/node_modules/ava/lib/test-worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/dharmik/Documents/Projects/klap/sls-node-rush-salad-analysis/node_modules/kvs-parser/index.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at extensions.<computed> (/home/dharmik/Documents/Projects/klap/sls-node-rush-salad-analysis/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.<computed> [as .js] (/home/dharmik/Documents/Projects/klap/sls-node-rush-salad-analysis/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/dharmik/Documents/Projects/klap/sls-node-rush-salad-analysis/test/issues/issue-384.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at extensions.<computed> (/home/dharmik/Documents/Projects/klap/sls-node-rush-salad-analysis/node_modules/require-precompiled/index.js:13:11) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/dharmik/Documents/Projects/klap/sls-node-rush-salad-analysis/node_modules/kvs-parser/index.js',
    '/home/dharmik/Documents/Projects/klap/sls-node-rush-salad-analysis/test/issues/issue-384.js',
    '/home/dharmik/Documents/Projects/klap/sls-node-rush-salad-analysis/node_modules/ava/lib/test-worker.js'
  ]
}
```

**Comment by dharmik-dalwadi-seaflux** [comment]
@piercus 
Closing this issue as this is fixed in version 0.0.3
